global:
  scrape_interval:     10s

alerting:
  alertmanagers:
  - static_configs:
    - targets:
       - "alertmanager:9093"

rule_files:
  - "/etc/prometheus/alerts.yml"

scrape_configs:

  - job_name: 'prometheus'
    static_configs:
    - targets: ['prometheus:9090']

  - job_name: 'node'
    static_configs:
    - targets: ['node-exporter:9100']

  - job_name: 'nginx'
    static_configs:
    - targets: ['nginx-exporter:9113']
